services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app #ホストマシンのfrontendディレクトリをコンテナの/appにマウント
    ports:
      - 3000:3000 #アプリケーションのポート
      - 9229:9229 #node.jsのデバッグポート
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gin
      POSTGRES_USER: ginuser
      POSTGRES_PASSWORD: ginpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

#再起動時にデータを保持する
volumes:
  postgres-init: {}
  postgres-data: {}

networks:
  ent-network:
    driver: bridge
