// Code generated by ent, DO NOT EDIT.

package movie

import (
	"project/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldDescription, v))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldDuration, v))
}

// Genre applies equality check predicate on the "genre" field. It's identical to GenreEQ.
func Genre(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldGenre, v))
}

// Director applies equality check predicate on the "director" field. It's identical to DirectorEQ.
func Director(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldDirector, v))
}

// Cast applies equality check predicate on the "cast" field. It's identical to CastEQ.
func Cast(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldCast, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldDescription, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v int) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...int) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...int) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v int) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v int) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v int) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v int) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldDuration, v))
}

// GenreEQ applies the EQ predicate on the "genre" field.
func GenreEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldGenre, v))
}

// GenreNEQ applies the NEQ predicate on the "genre" field.
func GenreNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldGenre, v))
}

// GenreIn applies the In predicate on the "genre" field.
func GenreIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldGenre, vs...))
}

// GenreNotIn applies the NotIn predicate on the "genre" field.
func GenreNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldGenre, vs...))
}

// GenreGT applies the GT predicate on the "genre" field.
func GenreGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldGenre, v))
}

// GenreGTE applies the GTE predicate on the "genre" field.
func GenreGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldGenre, v))
}

// GenreLT applies the LT predicate on the "genre" field.
func GenreLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldGenre, v))
}

// GenreLTE applies the LTE predicate on the "genre" field.
func GenreLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldGenre, v))
}

// GenreContains applies the Contains predicate on the "genre" field.
func GenreContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldGenre, v))
}

// GenreHasPrefix applies the HasPrefix predicate on the "genre" field.
func GenreHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldGenre, v))
}

// GenreHasSuffix applies the HasSuffix predicate on the "genre" field.
func GenreHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldGenre, v))
}

// GenreIsNil applies the IsNil predicate on the "genre" field.
func GenreIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldGenre))
}

// GenreNotNil applies the NotNil predicate on the "genre" field.
func GenreNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldGenre))
}

// GenreEqualFold applies the EqualFold predicate on the "genre" field.
func GenreEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldGenre, v))
}

// GenreContainsFold applies the ContainsFold predicate on the "genre" field.
func GenreContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldGenre, v))
}

// DirectorEQ applies the EQ predicate on the "director" field.
func DirectorEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldDirector, v))
}

// DirectorNEQ applies the NEQ predicate on the "director" field.
func DirectorNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldDirector, v))
}

// DirectorIn applies the In predicate on the "director" field.
func DirectorIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldDirector, vs...))
}

// DirectorNotIn applies the NotIn predicate on the "director" field.
func DirectorNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldDirector, vs...))
}

// DirectorGT applies the GT predicate on the "director" field.
func DirectorGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldDirector, v))
}

// DirectorGTE applies the GTE predicate on the "director" field.
func DirectorGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldDirector, v))
}

// DirectorLT applies the LT predicate on the "director" field.
func DirectorLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldDirector, v))
}

// DirectorLTE applies the LTE predicate on the "director" field.
func DirectorLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldDirector, v))
}

// DirectorContains applies the Contains predicate on the "director" field.
func DirectorContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldDirector, v))
}

// DirectorHasPrefix applies the HasPrefix predicate on the "director" field.
func DirectorHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldDirector, v))
}

// DirectorHasSuffix applies the HasSuffix predicate on the "director" field.
func DirectorHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldDirector, v))
}

// DirectorIsNil applies the IsNil predicate on the "director" field.
func DirectorIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldDirector))
}

// DirectorNotNil applies the NotNil predicate on the "director" field.
func DirectorNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldDirector))
}

// DirectorEqualFold applies the EqualFold predicate on the "director" field.
func DirectorEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldDirector, v))
}

// DirectorContainsFold applies the ContainsFold predicate on the "director" field.
func DirectorContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldDirector, v))
}

// CastEQ applies the EQ predicate on the "cast" field.
func CastEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldCast, v))
}

// CastNEQ applies the NEQ predicate on the "cast" field.
func CastNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldCast, v))
}

// CastIn applies the In predicate on the "cast" field.
func CastIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldCast, vs...))
}

// CastNotIn applies the NotIn predicate on the "cast" field.
func CastNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldCast, vs...))
}

// CastGT applies the GT predicate on the "cast" field.
func CastGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldCast, v))
}

// CastGTE applies the GTE predicate on the "cast" field.
func CastGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldCast, v))
}

// CastLT applies the LT predicate on the "cast" field.
func CastLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldCast, v))
}

// CastLTE applies the LTE predicate on the "cast" field.
func CastLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldCast, v))
}

// CastContains applies the Contains predicate on the "cast" field.
func CastContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldCast, v))
}

// CastHasPrefix applies the HasPrefix predicate on the "cast" field.
func CastHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldCast, v))
}

// CastHasSuffix applies the HasSuffix predicate on the "cast" field.
func CastHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldCast, v))
}

// CastIsNil applies the IsNil predicate on the "cast" field.
func CastIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldCast))
}

// CastNotNil applies the NotNil predicate on the "cast" field.
func CastNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldCast))
}

// CastEqualFold applies the EqualFold predicate on the "cast" field.
func CastEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldCast, v))
}

// CastContainsFold applies the ContainsFold predicate on the "cast" field.
func CastContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldCast, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.NotPredicates(p))
}
