// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project/internal/ent/item"
	"project/internal/ent/predicate"
	"project/internal/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	hooks    []Hook
	mutation *ItemMutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ItemUpdate) SetName(v string) *ItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableName(v *string) *ItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *ItemUpdate) SetPrice(v int) *ItemUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ItemUpdate) SetNillablePrice(v *int) *ItemUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ItemUpdate) AddPrice(v int) *ItemUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ItemUpdate) SetDescription(v string) *ItemUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableDescription(v *string) *ItemUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ItemUpdate) ClearDescription() *ItemUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSoldOut sets the "sold_out" field.
func (_u *ItemUpdate) SetSoldOut(v bool) *ItemUpdate {
	_u.mutation.SetSoldOut(v)
	return _u
}

// SetNillableSoldOut sets the "sold_out" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableSoldOut(v *bool) *ItemUpdate {
	if v != nil {
		_u.SetSoldOut(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ItemUpdate) SetUserID(v int) *ItemUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableUserID(v *int) *ItemUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ItemUpdate) SetUser(v *User) *ItemUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdate) Mutation() *ItemMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ItemUpdate) ClearUser() *ItemUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := item.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Item.price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := item.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Item.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Item.user"`)
	}
	return nil
}

func (_u *ItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(item.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(item.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(item.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(item.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SoldOut(); ok {
		_spec.SetField(item.FieldSoldOut, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.UserTable,
			Columns: []string{item.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.UserTable,
			Columns: []string{item.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemMutation
}

// SetName sets the "name" field.
func (_u *ItemUpdateOne) SetName(v string) *ItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableName(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *ItemUpdateOne) SetPrice(v int) *ItemUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillablePrice(v *int) *ItemUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ItemUpdateOne) AddPrice(v int) *ItemUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ItemUpdateOne) SetDescription(v string) *ItemUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableDescription(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ItemUpdateOne) ClearDescription() *ItemUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSoldOut sets the "sold_out" field.
func (_u *ItemUpdateOne) SetSoldOut(v bool) *ItemUpdateOne {
	_u.mutation.SetSoldOut(v)
	return _u
}

// SetNillableSoldOut sets the "sold_out" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableSoldOut(v *bool) *ItemUpdateOne {
	if v != nil {
		_u.SetSoldOut(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ItemUpdateOne) SetUserID(v int) *ItemUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableUserID(v *int) *ItemUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ItemUpdateOne) SetUser(v *User) *ItemUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdateOne) Mutation() *ItemMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ItemUpdateOne) ClearUser() *ItemUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdateOne) Where(ps ...predicate.Item) *ItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemUpdateOne) Select(field string, fields ...string) *ItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Item entity.
func (_u *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := item.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Item.price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := item.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Item.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Item.user"`)
	}
	return nil
}

func (_u *ItemUpdateOne) sqlSave(ctx context.Context) (_node *Item, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Item.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, item.FieldID)
		for _, f := range fields {
			if !item.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(item.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(item.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(item.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(item.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SoldOut(); ok {
		_spec.SetField(item.FieldSoldOut, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.UserTable,
			Columns: []string{item.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.UserTable,
			Columns: []string{item.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Item{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
