// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project/internal/ent/movie"
	"project/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovieUpdate is the builder for updating Movie entities.
type MovieUpdate struct {
	config
	hooks    []Hook
	mutation *MovieMutation
}

// Where appends a list predicates to the MovieUpdate builder.
func (_u *MovieUpdate) Where(ps ...predicate.Movie) *MovieUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MovieUpdate) SetTitle(v string) *MovieUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableTitle(v *string) *MovieUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MovieUpdate) SetDescription(v string) *MovieUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableDescription(v *string) *MovieUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MovieUpdate) ClearDescription() *MovieUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *MovieUpdate) SetDuration(v int) *MovieUpdate {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableDuration(v *int) *MovieUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *MovieUpdate) AddDuration(v int) *MovieUpdate {
	_u.mutation.AddDuration(v)
	return _u
}

// SetGenre sets the "genre" field.
func (_u *MovieUpdate) SetGenre(v string) *MovieUpdate {
	_u.mutation.SetGenre(v)
	return _u
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableGenre(v *string) *MovieUpdate {
	if v != nil {
		_u.SetGenre(*v)
	}
	return _u
}

// ClearGenre clears the value of the "genre" field.
func (_u *MovieUpdate) ClearGenre() *MovieUpdate {
	_u.mutation.ClearGenre()
	return _u
}

// SetDirector sets the "director" field.
func (_u *MovieUpdate) SetDirector(v string) *MovieUpdate {
	_u.mutation.SetDirector(v)
	return _u
}

// SetNillableDirector sets the "director" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableDirector(v *string) *MovieUpdate {
	if v != nil {
		_u.SetDirector(*v)
	}
	return _u
}

// ClearDirector clears the value of the "director" field.
func (_u *MovieUpdate) ClearDirector() *MovieUpdate {
	_u.mutation.ClearDirector()
	return _u
}

// SetCast sets the "cast" field.
func (_u *MovieUpdate) SetCast(v string) *MovieUpdate {
	_u.mutation.SetCast(v)
	return _u
}

// SetNillableCast sets the "cast" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableCast(v *string) *MovieUpdate {
	if v != nil {
		_u.SetCast(*v)
	}
	return _u
}

// ClearCast clears the value of the "cast" field.
func (_u *MovieUpdate) ClearCast() *MovieUpdate {
	_u.mutation.ClearCast()
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *MovieUpdate) SetReleaseDate(v time.Time) *MovieUpdate {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableReleaseDate(v *time.Time) *MovieUpdate {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// ClearReleaseDate clears the value of the "release_date" field.
func (_u *MovieUpdate) ClearReleaseDate() *MovieUpdate {
	_u.mutation.ClearReleaseDate()
	return _u
}

// Mutation returns the MovieMutation object of the builder.
func (_u *MovieUpdate) Mutation() *MovieMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MovieUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MovieUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovieUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := movie.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Movie.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Duration(); ok {
		if err := movie.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "Movie.duration": %w`, err)}
		}
	}
	return nil
}

func (_u *MovieUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(movie.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(movie.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(movie.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(movie.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(movie.FieldGenre, field.TypeString, value)
	}
	if _u.mutation.GenreCleared() {
		_spec.ClearField(movie.FieldGenre, field.TypeString)
	}
	if value, ok := _u.mutation.Director(); ok {
		_spec.SetField(movie.FieldDirector, field.TypeString, value)
	}
	if _u.mutation.DirectorCleared() {
		_spec.ClearField(movie.FieldDirector, field.TypeString)
	}
	if value, ok := _u.mutation.Cast(); ok {
		_spec.SetField(movie.FieldCast, field.TypeString, value)
	}
	if _u.mutation.CastCleared() {
		_spec.ClearField(movie.FieldCast, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(movie.FieldReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.ReleaseDateCleared() {
		_spec.ClearField(movie.FieldReleaseDate, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MovieUpdateOne is the builder for updating a single Movie entity.
type MovieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MovieMutation
}

// SetTitle sets the "title" field.
func (_u *MovieUpdateOne) SetTitle(v string) *MovieUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableTitle(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MovieUpdateOne) SetDescription(v string) *MovieUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableDescription(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MovieUpdateOne) ClearDescription() *MovieUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *MovieUpdateOne) SetDuration(v int) *MovieUpdateOne {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableDuration(v *int) *MovieUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *MovieUpdateOne) AddDuration(v int) *MovieUpdateOne {
	_u.mutation.AddDuration(v)
	return _u
}

// SetGenre sets the "genre" field.
func (_u *MovieUpdateOne) SetGenre(v string) *MovieUpdateOne {
	_u.mutation.SetGenre(v)
	return _u
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableGenre(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetGenre(*v)
	}
	return _u
}

// ClearGenre clears the value of the "genre" field.
func (_u *MovieUpdateOne) ClearGenre() *MovieUpdateOne {
	_u.mutation.ClearGenre()
	return _u
}

// SetDirector sets the "director" field.
func (_u *MovieUpdateOne) SetDirector(v string) *MovieUpdateOne {
	_u.mutation.SetDirector(v)
	return _u
}

// SetNillableDirector sets the "director" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableDirector(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetDirector(*v)
	}
	return _u
}

// ClearDirector clears the value of the "director" field.
func (_u *MovieUpdateOne) ClearDirector() *MovieUpdateOne {
	_u.mutation.ClearDirector()
	return _u
}

// SetCast sets the "cast" field.
func (_u *MovieUpdateOne) SetCast(v string) *MovieUpdateOne {
	_u.mutation.SetCast(v)
	return _u
}

// SetNillableCast sets the "cast" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableCast(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetCast(*v)
	}
	return _u
}

// ClearCast clears the value of the "cast" field.
func (_u *MovieUpdateOne) ClearCast() *MovieUpdateOne {
	_u.mutation.ClearCast()
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *MovieUpdateOne) SetReleaseDate(v time.Time) *MovieUpdateOne {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableReleaseDate(v *time.Time) *MovieUpdateOne {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// ClearReleaseDate clears the value of the "release_date" field.
func (_u *MovieUpdateOne) ClearReleaseDate() *MovieUpdateOne {
	_u.mutation.ClearReleaseDate()
	return _u
}

// Mutation returns the MovieMutation object of the builder.
func (_u *MovieUpdateOne) Mutation() *MovieMutation {
	return _u.mutation
}

// Where appends a list predicates to the MovieUpdate builder.
func (_u *MovieUpdateOne) Where(ps ...predicate.Movie) *MovieUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MovieUpdateOne) Select(field string, fields ...string) *MovieUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Movie entity.
func (_u *MovieUpdateOne) Save(ctx context.Context) (*Movie, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieUpdateOne) SaveX(ctx context.Context) *Movie {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MovieUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovieUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := movie.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Movie.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Duration(); ok {
		if err := movie.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "Movie.duration": %w`, err)}
		}
	}
	return nil
}

func (_u *MovieUpdateOne) sqlSave(ctx context.Context) (_node *Movie, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Movie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, movie.FieldID)
		for _, f := range fields {
			if !movie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != movie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(movie.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(movie.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(movie.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(movie.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(movie.FieldGenre, field.TypeString, value)
	}
	if _u.mutation.GenreCleared() {
		_spec.ClearField(movie.FieldGenre, field.TypeString)
	}
	if value, ok := _u.mutation.Director(); ok {
		_spec.SetField(movie.FieldDirector, field.TypeString, value)
	}
	if _u.mutation.DirectorCleared() {
		_spec.ClearField(movie.FieldDirector, field.TypeString)
	}
	if value, ok := _u.mutation.Cast(); ok {
		_spec.SetField(movie.FieldCast, field.TypeString, value)
	}
	if _u.mutation.CastCleared() {
		_spec.ClearField(movie.FieldCast, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(movie.FieldReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.ReleaseDateCleared() {
		_spec.ClearField(movie.FieldReleaseDate, field.TypeTime)
	}
	_node = &Movie{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
