// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project/internal/ent/movie"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovieCreate is the builder for creating a Movie entity.
type MovieCreate struct {
	config
	mutation *MovieMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *MovieCreate) SetTitle(v string) *MovieCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MovieCreate) SetDescription(v string) *MovieCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MovieCreate) SetNillableDescription(v *string) *MovieCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDuration sets the "duration" field.
func (_c *MovieCreate) SetDuration(v int) *MovieCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetGenre sets the "genre" field.
func (_c *MovieCreate) SetGenre(v string) *MovieCreate {
	_c.mutation.SetGenre(v)
	return _c
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_c *MovieCreate) SetNillableGenre(v *string) *MovieCreate {
	if v != nil {
		_c.SetGenre(*v)
	}
	return _c
}

// SetDirector sets the "director" field.
func (_c *MovieCreate) SetDirector(v string) *MovieCreate {
	_c.mutation.SetDirector(v)
	return _c
}

// SetNillableDirector sets the "director" field if the given value is not nil.
func (_c *MovieCreate) SetNillableDirector(v *string) *MovieCreate {
	if v != nil {
		_c.SetDirector(*v)
	}
	return _c
}

// SetCast sets the "cast" field.
func (_c *MovieCreate) SetCast(v string) *MovieCreate {
	_c.mutation.SetCast(v)
	return _c
}

// SetNillableCast sets the "cast" field if the given value is not nil.
func (_c *MovieCreate) SetNillableCast(v *string) *MovieCreate {
	if v != nil {
		_c.SetCast(*v)
	}
	return _c
}

// Mutation returns the MovieMutation object of the builder.
func (_c *MovieCreate) Mutation() *MovieMutation {
	return _c.mutation
}

// Save creates the Movie in the database.
func (_c *MovieCreate) Save(ctx context.Context) (*Movie, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MovieCreate) SaveX(ctx context.Context) *Movie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MovieCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MovieCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MovieCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Movie.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := movie.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Movie.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "Movie.duration"`)}
	}
	if v, ok := _c.mutation.Duration(); ok {
		if err := movie.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "Movie.duration": %w`, err)}
		}
	}
	return nil
}

func (_c *MovieCreate) sqlSave(ctx context.Context) (*Movie, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MovieCreate) createSpec() (*Movie, *sqlgraph.CreateSpec) {
	var (
		_node = &Movie{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(movie.Table, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(movie.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(movie.FieldDuration, field.TypeInt, value)
		_node.Duration = value
	}
	if value, ok := _c.mutation.Genre(); ok {
		_spec.SetField(movie.FieldGenre, field.TypeString, value)
		_node.Genre = value
	}
	if value, ok := _c.mutation.Director(); ok {
		_spec.SetField(movie.FieldDirector, field.TypeString, value)
		_node.Director = value
	}
	if value, ok := _c.mutation.Cast(); ok {
		_spec.SetField(movie.FieldCast, field.TypeString, value)
		_node.Cast = value
	}
	return _node, _spec
}

// MovieCreateBulk is the builder for creating many Movie entities in bulk.
type MovieCreateBulk struct {
	config
	err      error
	builders []*MovieCreate
}

// Save creates the Movie entities in the database.
func (_c *MovieCreateBulk) Save(ctx context.Context) ([]*Movie, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Movie, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MovieMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MovieCreateBulk) SaveX(ctx context.Context) []*Movie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MovieCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MovieCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
