// Code generated by ent, DO NOT EDIT.

package ent

import (
	"project/internal/ent/item"
	"project/internal/ent/schema"
	"project/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescName is the schema descriptor for name field.
	itemDescName := itemFields[0].Descriptor()
	// item.NameValidator is a validator for the "name" field. It is called by the builders before save.
	item.NameValidator = itemDescName.Validators[0].(func(string) error)
	// itemDescPrice is the schema descriptor for price field.
	itemDescPrice := itemFields[1].Descriptor()
	// item.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	item.PriceValidator = itemDescPrice.Validators[0].(func(int) error)
	// itemDescSoldOut is the schema descriptor for sold_out field.
	itemDescSoldOut := itemFields[3].Descriptor()
	// item.DefaultSoldOut holds the default value on creation for the sold_out field.
	item.DefaultSoldOut = itemDescSoldOut.Default.(bool)
	// itemDescUserID is the schema descriptor for user_id field.
	itemDescUserID := itemFields[4].Descriptor()
	// item.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	item.UserIDValidator = itemDescUserID.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescLoginID is the schema descriptor for login_id field.
	userDescLoginID := userFields[1].Descriptor()
	// user.LoginIDValidator is a validator for the "login_id" field. It is called by the builders before save.
	user.LoginIDValidator = userDescLoginID.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
}
