-- Create "items" table
CREATE TABLE "public"."items" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);
-- Create "movies" table
CREATE TABLE "public"."movies" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NULL,
  "duration" bigint NOT NULL,
  "genre" character varying NULL,
  "director" character varying NULL,
  "cast" character varying NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "login_id" character varying NOT NULL,
  "password" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_login_id_key" to table: "users"
CREATE UNIQUE INDEX "users_login_id_key" ON "public"."users" ("login_id");
