-- Create "movies" table
CREATE TABLE "public"."movies" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NULL,
  "duration" bigint NOT NULL,
  "genre" character varying NULL,
  "director" character varying NULL,
  "cast" character varying NULL,
  "release_date" timestamptz NULL,
  "rating" character varying NULL,
  "score" double precision NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "login_id" character varying NOT NULL,
  "password" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_login_id_key" to table: "users"
CREATE UNIQUE INDEX "users_login_id_key" ON "public"."users" ("login_id");
-- Create "items" table
CREATE TABLE "public"."items" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "price" bigint NOT NULL,
  "description" character varying NULL,
  "sold_out" boolean NOT NULL DEFAULT false,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "items_users_items" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
